#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=99
USE_PROCD=1

start_service()
{
	source /etc/openwrt_release
          echo "                                                               " > /etc/banner
	  echo " 888b     d888 Y88b   d88P 888       888 8888888b. 88888888888" >> /etc/banner 
          echo " 8888b   d8888  Y88b d88P  888   o   888 888   Y88b    888" >> /etc/banner     
          echo " 88888b.d88888   Y88o88P   888  d8b  888 888    888    888" >> /etc/banner     
          echo " 888Y88888P888    Y888P    888 d888b 888 888   d88P    888" >> /etc/banner     
          echo " 888 Y888P 888     888     888d88888b888 8888888P     888" >> /etc/banner     
          echo " 888  Y8P  888     888     88888P Y88888 888 T88b      888" >> /etc/banner     
          echo " 888       888     888     8888P   Y8888 888  T88b     888" >> /etc/banner     
          echo " 888       888     888     888P     Y888 888   T88b    888" >> /etc/banner      
          echo "       Cutomize by SopekSemprit(MALAYSIA OPENWRT)" >> /etc/banner
          echo "           Powered by abidarwish & Solomonricky" >> /etc/banner
          echo "  -----------------------------------------------------" >> /etc/banner
          echo "                 MYWRT_MALAYSIA OPENWRT   " >> /etc/banner
          echo "  -----------------------------------------------------" >> /etc/banner
}
